# # Copyright (c) Meta Platforms, Inc. and affiliates.
# # All rights reserved.

# """
# FastAPI application for Adaptive Driving Environment (OpenEnv compliant)

# Endpoints (auto-generated by OpenEnv):
#     - POST /reset
#     - POST /step
#     - GET /state
#     - GET /schema
#     - WS /ws

# Optional:
#     - GET /demo (simple UI)
# """

# # ---------------- OpenEnv App ----------------

# try:
#     from openenv.core.env_server.http_server import create_app
# except Exception as e:
#     raise ImportError(
#         "openenv is required. Install using:\n\npip install openenv"
#     ) from e


# # ✅ Correct imports
# from models import AdaptiveDrivingAction, AdaptiveDrivingObservation
# from server.adaptive_driving_env_environment import AdaptiveDrivingEnvironment


# # ✅ Create OpenEnv app (MANDATORY)
# app = create_app(
#     AdaptiveDrivingEnvironment,
#     AdaptiveDrivingAction,
#     AdaptiveDrivingObservation,
#     env_name="adaptive_driving_env",
#     max_concurrent_envs=1,  # allow parallel sessions
# )


# # ---------------- Optional Demo UI ----------------

# from fastapi.responses import HTMLResponse


# @app.get("/demo", response_class=HTMLResponse)
# def demo_ui():
#     return """
#     <html>
#     <head>
#         <title>🚗 Adaptive Driving AI</title>
#     </head>
#     <body style="text-align:center; font-family:sans-serif">

#         <h1>🚗 Adaptive Driving Simulation</h1>
#         <button onclick="run()">Run Simulation</button>

#         <pre id="output" style="margin-top:20px;"></pre>

#         <script>
#         async function run() {
#             let res = await fetch('/reset', { method: 'POST' });
#             let data = await res.json();

#             let output = "";

#             for (let i = 0; i < 20; i++) {
#                 res = await fetch('/step', {
#                     method: 'POST',
#                     headers: { 'Content-Type': 'application/json' },
#                     body: JSON.stringify({
#                         action: { move: "accelerate" }
#                     })
#                 });

#                 data = await res.json();

#                 const obs = data.observation;

#                 output += `Step ${i+1}: Pos=${obs.position}, Speed=${obs.speed}, Battery=${obs.battery}, Reward=${obs.reward}\\n`;

#                 if (data.done) break;
#             }

#             document.getElementById("output").innerText = output;
#         }
#         </script>

#     </body>
#     </html>
#     """




# # ---------------- Local Run ----------------

# def main():
#     import uvicorn
#     uvicorn.run("server.app:app", host="0.0.0.0", port=8000, reload=True)


# if __name__ == "__main__":
#     main()